Added default export to CommonJS variants
ljharb/es-get-iterator pull request #11
Opened 2021-02-23 08:29 UTC by JasonHK

I currently writing a TypeScript definition for this package on DefinitelyTyped/DefinitelyTyped#51389. Adding a default export to CommonJS variants could avoid confusion to the users.

2021-02-23 15:36 UTC, ljharb commented
This seems like it would add confusion. Nothing should ever have a .default property; that’s an implementation detail of module transpilation.

2021-02-23 15:40 UTC, ljharb requested changes
This seems like it would add confusion. Nothing should ever have a .default property; that’s an implementation detail of module transpilation.

2021-02-23 16:23 UTC, JasonHK commented
> This seems like it would add confusion. Nothing should ever have a .default property; that’s an implementation detail of module transpilation.

@ljharb Wouldn't this cause issue when using the TypeScript definition? Since the CommonJS version of the module was `function getIterator() {...}`, but the ESM one was `{ default: function getIterator() {...} }`.

2021-02-23 16:25 UTC, ljharb commented
The ESM one isn’t that, though - that object would be similar to the module namespace object, sure, but that’s how it’s supposed to be. CJS modules only have a default export.

2021-02-23 16:59 UTC, JasonHK commented
> The ESM one isn’t that, though - that object would be similar to the module namespace object, sure, but that’s how it’s supposed to be. CJS modules only have a default export.

@ljharb But which export syntax I should use in the definition? Since this package used conditional exports, I thought adding `module.exports.default` to the CommonJS variant, then modify the definition to `export default function getIterator<T>(iterable: T): InferIterable<T>;` would provide maximum compatibility (because this way does not require the used of `esModuleInterop`).

2021-02-23 17:21 UTC, ljharb commented
`export = blah` is usually how it's done, i think?

`esModuleInterop` *should* be required, as TS's module system is broken without it.

2021-02-24 05:28 UTC, JasonHK commented
> The ESM one isn’t that, though - that object would be similar to the module namespace object, sure, but that’s how it’s supposed to be. CJS modules only have a default export.

@ljharb Okay, I figured it out now.

2021-02-24 05:28 UTC, closed without merging